#include "navcore/navcore.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>
#include <stdexcept>
namespace navcore { namespace { constexpr double pi=3.14159265358979323846, max_match_m=200.0; double deg(double x){return x*180/pi;} double bearing(const Node&a,const Node&b){double y=std::sin((b.longitude-a.longitude)*pi/180)*std::cos(b.latitude*pi/180),x=std::cos(a.latitude*pi/180)*std::sin(b.latitude*pi/180)-std::sin(a.latitude*pi/180)*std::cos(b.latitude*pi/180)*std::cos((b.longitude-a.longitude)*pi/180);return std::fmod(deg(std::atan2(y,x))+360,360);} double diff(double a,double b){double d=std::fabs(a-b);return d>180?360-d:d;} std::vector<MatchResult> candidates(const RoadGraph&g,const GpsPoint&p){std::vector<MatchResult> r;for(const auto&n:g.nodes())for(const auto&e:g.outgoing(n.first)){const auto&a=g.node(e.from),&b=g.node(e.to);double k=111320,dx=(b.longitude-a.longitude)*k*std::cos(p.latitude*pi/180),dy=(b.latitude-a.latitude)*k,px=(p.longitude-a.longitude)*k*std::cos(p.latitude*pi/180),py=(p.latitude-a.latitude)*k,q=dx*dx+dy*dy,t=q?std::clamp((px*dx+py*dy)/q,0.0,1.0):0,dist=std::hypot(px-t*dx,py-t*dy),hd=p.heading_deg?diff(*p.heading_deg,bearing(a,b)):0;if(dist<=max_match_m)r.push_back({e,e.osm_way_id,e.road_name,a.latitude+t*(b.latitude-a.latitude),a.longitude+t*(b.longitude-a.longitude),dist,hd,dist+hd*.25,0});}for(auto&m:r)m.candidate_count=r.size();std::sort(r.begin(),r.end(),[](const auto&a,const auto&b){return a.score<b.score;});if(r.size()>6)r.resize(6);return r;} }
std::vector<GpsPoint> load_gps_trace(const std::string&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open GPS trace: "+p);std::vector<GpsPoint> r;std::string l;std::getline(in,l);while(std::getline(in,l)){std::stringstream s(l);std::string a,b,c;std::getline(s,a,',');std::getline(s,b,',');std::getline(s,c,',');r.push_back({std::stod(a),std::stod(b),c.empty()?std::optional<double>{}:std::optional<double>{std::stod(c)}});}return r;}
MatchResult match_point(const RoadGraph&g,const GpsPoint&p){auto c=candidates(g,p);if(c.empty())throw std::runtime_error("unmatched: GPS point exceeds max-match-distance");return c.front();}
std::vector<MatchResult> match_sequence(const RoadGraph&g,const std::vector<GpsPoint>&ps){if(ps.empty())return{};std::vector<std::vector<MatchResult>> cs;for(const auto&p:ps){auto c=candidates(g,p);if(c.empty())throw std::runtime_error("unmatched: GPS point exceeds max-match-distance");cs.push_back(std::move(c));}std::vector<std::vector<double>> dp(cs.size());std::vector<std::vector<size_t>> prev(cs.size());for(size_t i=0;i<cs.size();++i){dp[i].assign(cs[i].size(),std::numeric_limits<double>::infinity());prev[i].assign(cs[i].size(),0);}for(size_t j=0;j<cs[0].size();++j)dp[0][j]=cs[0][j].score;for(size_t i=1;i<cs.size();++i)for(size_t j=0;j<cs[i].size();++j)for(size_t k=0;k<cs[i-1].size();++k){double transition=cs[i][j].osm_way_id==cs[i-1][k].osm_way_id?0.0:8.0;if(cs[i][j].matched_edge.from!=cs[i-1][k].matched_edge.to)transition+=2.0;double v=dp[i-1][k]+cs[i][j].score+transition;if(v<dp[i][j]){dp[i][j]=v;prev[i][j]=k;}}size_t j=std::min_element(dp.back().begin(),dp.back().end())-dp.back().begin();std::vector<MatchResult> out(cs.size());for(size_t i=cs.size();i-->0;){out[i]=cs[i][j];out[i].score=dp[i][j];if(i)j=prev[i][j];}return out;}
}